name: Build & Test & Deploy
on: [push]

jobs:
  build-npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          GOOGLE_MAPS_STATIC_API_KEY: ${{ secrets.GOOGLE_MAPS_STATIC_API_KEY }}
      - name: Upload dist files
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/

  quality-lint:
    runs-on: ubuntu-latest
    needs: build-npm
    steps:
      - uses: actions/checkout@v2
      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Run linter
        run: npm run lint

  quality-test:
    runs-on: ubuntu-latest
    needs: build-npm
    steps:
      - uses: actions/checkout@v2
      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Run tests
        run: npm test

  deploy-ghcr:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build-npm, quality-test]
    steps:
      - uses: actions/checkout@v2
      - name: Download dist files
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            GIT_COMMIT="${{ github.sha }}"
            VERSION="${{ github.ref_name }}"
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  deploy-gcs:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build-npm, quality-test]
    steps:
      - uses: actions/checkout@v2
      - name: Download dist files
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public/
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Upload to Google Cloud Storage
        run: |
          gsutil -m rsync -d -r public 'gs://${{ secrets.GOOGLE_CLOUD_BUCKET }}'
          echo -e "\nset cache-control:public, max-age=0, must-revalidate on **.html"
          gsutil -m setmeta -h "Cache-Control:public, max-age=0, must-revalidate" 'gs://${{ secrets.GOOGLE_CLOUD_BUCKET }}/**.html'
          echo -e "\nset cache-control:public, max-age=31536000, immutable on **.js"
          gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" 'gs://${{ secrets.GOOGLE_CLOUD_BUCKET }}/**.js'
          echo -e "\nset cache-control:public, max-age=31536000, immutable on **.css"
          gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" 'gs://${{ secrets.GOOGLE_CLOUD_BUCKET }}/**.css'
          echo -e "\nset cache-control:public, max-age=31536000, immutable on static/*"
          gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" 'gs://${{ secrets.GOOGLE_CLOUD_BUCKET }}/static/*'
          echo -e "\nset \"cache-control:public, max-age=0, must-revalidate\" on page-data/**.json"
          gsutil -m setmeta -h "Cache-Control:public, max-age=0, must-revalidate" 'gs://${{ secrets.GOOGLE_CLOUD_BUCKET }}/page-data/**.json'
          echo -e "\nset \"cache-control:public, max-age=0, must-revalidate\" on sw.js"
          gsutil -m setmeta -h "Cache-Control:public, max-age=0, must-revalidate" 'gs://${{ secrets.GOOGLE_CLOUD_BUCKET }}/sw.js'
        env:
          GOOGLE_CLOUD_BUCKET: ${{ secrets.GOOGLE_CLOUD_BUCKET }}
